### ISSUE TITLE
Parse endpoint's json keys are all lowercase, unlike the metar endpoint

### ISSUE THREAD

**Issue by mralext20** [flyinactor91/AVWX-API#10]
see title.

**Comment by flyinactor91** [comment]
I accidentally overwrote the existing parse endpoint with a major update earlier this week. The GET method should be working again with the old response structure. However, this will be replaced/removed later this year with the new format found on the POST method. Preview docs can be found here:

https://avwx.docs.apiary.io

And the site documentation will be updated/removed this weekend to reflect the upcoming changes.

**Comment by flyinactor91** [comment]
All components related to the "preview" endpoint and documentation are now in place. The new format will become the default on April 1st, 2019.
