### ISSUE TITLE
[Feature Request] Age indicator on METAR reports

### ISSUE THREAD

**Issue by mralext20** [flyinactor91/AVWX-API#9]
useful for more easily knowing how old the data received is.

**Comment by JanC** [comment]
Use the `Time` property to calculate the date

**Comment by mralext20** [comment]
Unfortunately, the `Time` property does not include the month or year,
making it non trivial around end of month or end of year calculations.

**Comment by flyinactor91** [comment]
A pull request was made to AVWX-Engine which added this functionality to the core, but it has not been implemented in the client or on the API yet. I agree that this should be added, and it will be developed from the bottom and make its way into the API.

**Comment by flyinactor91** [comment]
This functionality has been added and is currently available on the preview endpoints:

https://avwx.rest/api/preview/metar/KJFK

`"time":{"dt":"Fri, 07 Sep 2018 13:51:00 GMT","repr":"071351Z"}`
